premier commit pour feedback :)
osunyorg/theme pull request #311
Opened 2024-02-23 15:48 UTC by Clararigaud

@alexisben  coucou voilà le premier jet ( je pense que c'est pas top au niveau des gestions plaine page / sidebar, j'avais pas encore rencontré ces cas e figure j'ai un peu improvisé)

2024-02-26 09:38 UTC, alexisben commented on layouts/partials/blocks/templates/programs.html
> +          </article>
il manque une indentation

2024-02-26 09:41 UTC, alexisben commented
Ça ne fonctionne pas si je veux tester en local sur le site Example, quelle procédure pour tester ta branche ?

2024-02-27 10:00 UTC, alexisben commented on assets/sass/_theme/blocks/programs.sass
> +                        color: $block-call-to-action-button-hover-color
Tu peux simplifier ! Il vaut mieux qu'il soit simple comme pour les blocs actualités par exemple. Une variable qui porte le nom d'un bloc ne devrait avoir d'incidence que sur ce même bloc

2024-03-05 09:01 UTC, alexisben requested changes

2024-03-05 09:01 UTC, alexisben commented on assets/sass/_theme/blocks/programs.sass
> +            flex-direction: column-reverse
Pour éviter des alignements étranges sur des vieux navigateur et dans un soucis de cohérence tu peux utiliser un ```order``` plutôt que le ```column-reverse```. L'usage de order permet aussi de pouvoir d'insérer d'autres éléments (entre le media et le contenu texte par exemple) et de le placer visuellement au bon endroit et sémantiquement à un autre.

2024-03-05 15:04 UTC, Clararigaud commented
Edited ! J'ai aussi ajouté une entrée dans config pour les tailles d'images

2024-03-06 11:24 UTC, alexisben approved these changes

2024-03-06 11:25 UTC, merged