Ne pas lister la page racine (pages) dans le plan du site
osunyorg/theme pull request #348
Opened 2024-03-19 15:49 UTC by arnaudlevy

2024-03-20 08:22 UTC, alexisben requested changes
C'est chouette merci ! En terme d'ordre, c'est normal de mettre les pages après les autres sections ?

2024-03-20 08:22 UTC, alexisben commented on assets/sass/_theme/sections/sitemap.sass
> +                        &::before
@arnaudlevy tu peux enlever le sélecteur ```&::before```, car le mixin ```icon``` sert aussi de sélecteur

```suggestion
                        @include icon(list-hyphen)
                            position: absolute
                            left: pxToRem(-24)
                            font-size: pxToRem(24)
```

2024-03-20 08:22 UTC, alexisben commented on assets/sass/_theme/sections/sitemap.sass
> +                            font-size: pxToRem(24)
Utiliser $spacing-3

2024-03-20 08:22 UTC, alexisben commented on layouts/pages/sitemap.html
> +            <div class="block-content">
```suggestion
            <div class="block-content">
```

2024-03-20 08:22 UTC, alexisben commented on layouts/pages/sitemap.html
> +          <h2>Pages</h2>
i18n

2024-03-20 14:47 UTC, arnaudlevy commented on assets/sass/_theme/sections/sitemap.sass
> +                            font-size: pxToRem(24)
pour une font-size ? c'est trop bizarre non ?

2024-03-20 14:49 UTC, arnaudlevy commented
Ah ben non t'as raison

2024-03-21 15:33 UTC, alexisben commented on assets/sass/_theme/sections/sitemap.sass
> +                            font-size: pxToRem(24)
ah pardon c'est pour le left !

2024-03-21 15:36 UTC, alexisben approved these changes

2024-03-21 15:36 UTC, merged