Campus map
osunyorg/theme pull request #404
Opened 2024-04-29 15:42 UTC by Clararigaud

Ajout de la map dans la page campus (locations)

2024-04-29 16:48 UTC, Clararigaud commented
Il y a un probleme sur safari pour la popup, la librairie leaflet ne calcule pas la largeur de la popup de la meme maniere on dirait, je trouve pas comment solutionner... vous avez une idée ?

2024-04-30 13:21 UTC, Clararigaud commented on assets/sass/_theme/sections/locations.sass
> +        padding-bottom: 0px
Je peux ajouter une classe au body dans  campus.js ?

2024-04-30 13:42 UTC, Clararigaud commented on assets/sass/_theme/sections/locations.sass
> +                    grid-template: "a b"
Leaflet calcule mal la largeur quand j'utilise un flex, j'ignore pourquoi ( et du coup il y a ce problème avec safari aussi)

2024-05-02 08:37 UTC, alexisben requested changes

2024-05-02 08:37 UTC, alexisben commented on assets/sass/_theme/sections/locations.sass
> +        padding-bottom: 0px
Carrément sur <main> ! Tu peux ajouter une classe "page-with-map" pour être iso avec "page-with-blocks"

dans themes/osuny-hugo-theme-aaa/assets/sass/_theme/design-system/layout.sass :

```
main
    &:not(.page-with-blocks)
        padding-bottom: $spacing-5
```

2024-05-02 09:25 UTC, alexisben commented
C'est très chelou comment chrome l'interprète, tu sais pq ?

![image](https://github.com/osunyorg/theme/assets/4630530/1bdad786-4ea4-47fc-8f85-41694594584c)

![image](https://github.com/osunyorg/theme/assets/4630530/20f62c16-4971-4bc2-829f-fc635ba13fae)

2024-05-02 09:28 UTC, alexisben requested changes

2024-05-02 09:28 UTC, alexisben commented on assets/sass/_theme/sections/locations.sass
> +                mask: url("/assets/images/map-popup.svg") no-repeat 50% 0%
Ok j'avais pas compris à quoi ça servait, tu peux faire un triangle avec du CSS, ça évite une requête un fichier svg en plus ! Tu peux utiliser un outil genre https://outils-css.aliasdmc.fr/generateur-de-triangles-css.php

2024-05-02 18:06 UTC, alexisben commented on layouts/partials/locations/map.html
> +    <article class="campus" data-longitude="{{ .Params.contact_details.geolocation.longitude }}"data-latitude="{{ .Params.contact_details.geolocation.latitude }}">
manque une indentation sur article

2024-05-05 08:08 UTC, merged