added config for key figures animation for block
osunyorg/theme pull request #451
Opened 2024-06-03 15:02 UTC by Olivia206

## Type

- [X] Nouvelle fonctionnalité
- [ ] Bug
- [ ] Ajustement
- [ ] Rangement

## Description

Ajout de la possibilité de désactiver de façon globale les animations du block key figures.

```
  blocks:
    key_figures:
      animation: true
```

## Niveau d'incidence

- [X] Incidence faible 😌
- [ ] Incidence moyenne 😲
- [ ] Incidence forte 😱

## Référence (ticket et/ou figma)

#434 

## URL de test sur example.osuny.org

`/fr/blocks/blocks-narratifs/chiffre-cles/`

## URL de test du site (optionnel)

Sur le [rapport openclassroom](https://github.com/osunyorg/openclassrooms-rapport-2023) : `/en/our-mission/`
(Il faut mettre à false dans la config)

## Screenshots

N/A

2024-06-03 19:45 UTC, alexisben requested changes

2024-06-03 19:45 UTC, alexisben commented on config.yaml
> +      animation: true
```suggestion
      animated: true
```

2024-06-03 19:45 UTC, alexisben commented on layouts/partials/blocks/templates/key_figures.html
> +{{- $isAnimated := site.Params.blocks.key_figures.animation -}}
```suggestion
{{- $isAnimated := site.Params.blocks.key_figures.animated -}}
```

2024-06-03 19:45 UTC, alexisben commented on layouts/partials/blocks/templates/key_figures.html
> +  <div class="{{ $block_class }} {{- if $isAnimated }} with-animation {{ end }}">
```suggestion
  <div class="{{ $block_class }} {{- if $isAnimated }} is-animated {{ end }}">
```

2024-06-03 19:45 UTC, alexisben commented on assets/js/theme/blocks/keyFigures.js
> +    const keyFigures = document.querySelectorAll('.block-key_figures.with-animation');
```suggestion
    const keyFigures = document.querySelectorAll('.block-key_figures.is-animated');
```

2024-06-04 07:49 UTC, Olivia206 commented
C'est good pour les changements que tu as proposé @alexisben, merci !

2024-06-06 10:31 UTC, alexisben commented
Attention pas le même rendu :

Après animation :

![image](https://github.com/osunyorg/theme/assets/4630530/a3b2263e-5123-46a4-b391-fca6447cb662)

Sans animation : 

![image](https://github.com/osunyorg/theme/assets/4630530/a0f15414-5522-459b-a44c-969b6bd9b86a)

2024-06-06 13:55 UTC, Olivia206 commented
J'ai ajouté les espaces avec hugo
J'ai aussi fait un petit fix pour les virgules quand la valeur est grande, elles apparaissaient au 2e millier avec le js

2024-06-06 17:49 UTC, alexisben requested changes

2024-06-06 17:49 UTC, alexisben commented on assets/js/theme/blocks/keyFigures.js
> +        this.isAnimated = this.dom.classList.contains('is-animated') ? true : false;
Tu n'as pas besoin de la condition ternaire ici car contains() renvoie un booléen déjà 

```suggestion
        this.isAnimated = this.dom.classList.contains('is-animated');
```

2024-06-06 17:49 UTC, alexisben commented on assets/js/theme/blocks/keyFigures.js
> +        return value.toLocaleString('en').replace(/,/g, separator);
c'est mieux en regex qu'en string ?

2024-06-07 07:55 UTC, Olivia206 commented on assets/js/theme/blocks/keyFigures.js
> +        this.isAnimated = this.dom.classList.contains('is-animated') ? true : false;
ah mais oui, merci !

2024-06-07 07:55 UTC, Olivia206 commented on assets/js/theme/blocks/keyFigures.js
> +        return value.toLocaleString('en').replace(/,/g, separator);
ok !

2024-06-07 08:38 UTC, alexisben approved these changes

2024-06-07 08:38 UTC, merged