Slider lightbox
osunyorg/theme pull request #642
Opened 2024-10-07 13:40 UTC by Clararigaud

## Type

- [ ] Nouvelle fonctionnalité
- [ ] Bug
- [x] Ajustement
- [x] Rangement

## Description
Correctifs slider et nouvelle lightbox

## Niveau d'incidence

- [ ] Incidence faible 😌
- [x] Incidence moyenne 😲
- [ ] Incidence forte 😱

## Référence (ticket et/ou figma)
https://www.figma.com/design/tQh3oLfNwSt8aoVDuUjQt0/Th%C3%A8me-Osuny?node-id=10638-2274&t=TIVm8wHc5oj7JEOM-1

## URL de test sur example.osuny.org

[branch]--example.osuny.netlify.app

## URL de test du site (optionnel)

## Screenshots

2024-10-07 14:09 UTC, Clararigaud commented
* remplacer les tabindex="0" sur les figure par des tabindex="-1"
* ajouter sur les figure un aria-label="contenu de la légende" et un role="figure"
* mettre les liens dans les figure avec aria-hidden="true" en tabindex="-1"
* supprimer le title et le aria-label des liens qui affichent les images dans une modale 
* modifier le texte dans les liens qui affichent les images dans une modale par "agrandir l'image xxx" où xxx = alternative de l'image (ou mettre l'image dans le lien et changer juste ouvrir par agrandir)
* sur les boutons < et > la valeur du aria-describedby doit etre l'id du titre du carrousel et non du conteneur des slides (le probleme remonté doit venir de la je pense)

2024-10-08 18:15 UTC, alexisben commented
Bloc timeline en pleine largeur : l'overflow n'est pas correct à gauche

<img width="470" alt="image" src="https://github.com/user-attachments/assets/ae0ddb17-ede5-4851-ad03-9836785baa57">

Bloc galerie : 
- [ ] en pleine largeur l'overflow doit courir sur la largeur de l'écran

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/71cab65e-cc1e-47c8-8dbd-4754eabe7f64">

- [ ] en sidebar sur grand écran les images doivent courir jusqu'au bord de l'écran

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/8301970c-b344-41e3-a000-90ff864dbb1d">


Bloc post : comme il n'y a plus d'overflow sous la toc, enlever l'effet d'opacité sur les posts précédents

https://github.com/user-attachments/assets/277a03b3-3d5a-49bc-876f-391b6b8df228

2024-10-08 18:44 UTC, alexisben commented
Je vois que tu as ajouté du schema.org sur les item des timeline, mais j'ai un gros doute sur la nature `Article` : https://schema.org/Article 

Comme c'est à la fois sur le vertical et l'horizontal, je me dis que c'est volontaire ? 

https://github.com/osunyorg/theme/blob/c027de7160ba64201c1af4fcfd3c70ccda72c0a6/layouts/partials/blocks/templates/timeline/vertical.html
`<article class="timeline-event" itemscope itemtype="https://schema.org/Article">`

2024-10-08 18:57 UTC, alexisben commented
Le partial carousel.html n'a rien à faire ici, les fichiers à la racine de `partials/blocks/templates` représente les différents type de bloc, tu peux le mettre dans `partials/commons` car c'est un partiel commun.

<img width="429" alt="image" src="https://github.com/user-attachments/assets/419291d2-7058-43ed-a854-e96e220083a0">

2024-10-08 18:58 UTC, alexisben commented
Pour ces deux fichiers, c'est pas nécessaire de préfixer avec `lightbox-` car ils sont dans le dossier `lightbox` c'est suffisant

<img width="311" alt="image" src="https://github.com/user-attachments/assets/5c1fc870-3d1b-4282-9717-16869a3be69c">

2024-10-09 04:37 UTC, alexisben requested changes
C'est pas possible de venir conditionner des partiel comme `blocks/top` ou `image-figure` avec des conditions du carousel ! pour te donner une idée`image-figure` c'est compilé 681 fois dans bdx montaigne et `block-top` 1376 fois.

Est-ce qu'il y a d'autre trucs comme ça à remonter dans la PR du slider déjà merge sur `main` ?

2024-10-09 04:37 UTC, alexisben commented on layouts/partials/blocks/top.html
> +{{ end }}
Ce partiel est propre et clean, pourquoi je vois du `carousel` dedans ? tu ajoutes un id `xx-carousel`sur les titres de TOUS les blocks là

2024-10-09 04:37 UTC, alexisben commented on layouts/partials/commons/image-figure.html
> +              role="figure"
c'est une reco temesis ? <figure role="figure"> ?

2024-10-09 04:42 UTC, alexisben commented
Sérieusement, le balisage est toujours cassé et le partiel `posts/post.html` est toujours pourri par des conditions pour le carousel ! 

<img width="598" alt="image" src="https://github.com/user-attachments/assets/640fc899-65a6-4acb-807b-f68c9d72e038">

2024-10-09 04:43 UTC, alexisben commented
Reprends le ticket : https://github.com/osunyorg/theme/issues/621

2024-10-09 08:23 UTC, Clararigaud commented
# Synthese des modifications: 

## Prioritaire

- [ ] DOM post: enlever les` <li>`
- [ ] DOM: enlever les tests is_carousel dans image_figure.html
- [ ] DOM: enlever le test is_carousel dans top.html
- [ ] Layout à homogeniser ( témoignages / figures / gallerie )
- [ ] Focus sur le nouveau slide apparent
- [ ] Gallerie: tests du conflit avec le focus auto
- [ ] Changer le inert utilisé dans la lightbox
- [ ] Les elements non visibles doivent etre mis à aria-hidden true ainsi que les enfants
- [ ] Supprimer le schema dans timeline

## Secondaire
- [ ] Affichage du menu generant un resize qui fait sauter la page
- [ ] Gallerie: Gestion du load des images et hauteur en js
- [ ] Renommage de fichiers et rangement

2024-10-09 14:38 UTC, Clararigaud commented
# Note concernant le style de la timeline en affichage barre latérale: 
je n'ai pas réussi à obtenir un overflow laissant apparaitre le slide passé en semi transparence, comme indiqué sur la maquette figma. 
L'usage du overflow scroll sur le composant slider en est la raison. 
En effet, un overflow scroll est incompatible avec un overflow visible.
L'alternative possible est de décaller le contenu du slider à l'interieur du carousel, d'une distance correspondant à la distance offset(4), dans le javascript. 
La conséquence de cela est l'ajout d'une condition en javascript sur le cas "barre-laterale" qui permettra de déduire le bon index de slide en fonction de sa position.
Une solution plus simple existe peut etre, je ne l'ai pas trouvée pour l'heure.

2024-10-09 16:40 UTC, Clararigaud commented on layouts/partials/commons/image-figure.html
> +              role="figure"
oui

2024-10-10 08:58 UTC, Olivia206 commented
J'ai ajouté une issue relative au titre dans l'admin : https://github.com/osunyorg/admin/issues/2305

2024-10-14 13:00 UTC, Clararigaud commented
Merge conflicts resolved

2024-10-21 07:53 UTC, merged