Gestion des métadonnées spécifiques à la recherche (Google Scholar)
osunyorg/theme pull request #741
Opened 2024-11-20 14:18 UTC by Olivia206

## Type

- [ ] Nouvelle fonctionnalité
- [ ] Bug
- [X] Ajustement
- [ ] Rangement

## Description

Ajout de méta-données permettant un meilleur référencement dans google scolars.

J'ai mis l'accent sur les papiers, est-ce aussi un sujet pour les publications ? 

## Niveau d'incidence

- [X] Incidence faible 😌
- [ ] Incidence moyenne 😲
- [ ] Incidence forte 😱

## Référence (ticket et/ou figma)

https://github.com/osunyorg/theme/issues/595

## URL de test du site Drgrowth Journal

http://localhost:1313/publications/2023-10-11-preparing-for-the-degrowth-transition-in-healthcare-understanding-the-challenges-and-opportunities/

## Screenshots

![Capture d’écran 2024-11-20 à 15 16 06](https://github.com/user-attachments/assets/7decc8c5-d20d-421b-b11a-22202973ac27)

2024-12-02 13:50 UTC, alexisben requested changes

2024-12-02 13:50 UTC, alexisben commented on layouts/partials/papers/citation-tags.html
> +{{ $date := .Params.dates.published}}
```suggestion
{{ $date := .Params.dates.published }}
```

2024-12-02 13:50 UTC, alexisben commented on layouts/partials/papers/citation-tags.html
> +  <meta name="citation_journal_title" content="{{ .Title }}">
```suggestion
  <meta name="citation_journal_title" content="{{- .Title -}}">
```

2024-12-04 06:31 UTC, arnaudlevy commented
Ah oui mince

2024-12-04 08:30 UTC, arnaudlevy commented
J'ai fix ici https://github.com/osunyorg/admin/commit/e63d993c892472cd9a9d425a41c8859097476c25

@Olivia206 tu peux réessayer dans 15 mn stp ?

2024-12-04 08:31 UTC, arnaudlevy commented
C'est une url de download, mieux que juste l'url directe je pense (il y a le type et le nom de fichier)

2024-12-04 17:36 UTC, arnaudlevy commented on layouts/partials/head/seo.html
> +{{ if eq .Section "papers" }}
mon idée était plutôt que, de manière générale, si t'as un nœud metadata tu l'affiches

2024-12-04 17:36 UTC, arnaudlevy commented on layouts/partials/papers/citation-tags.html
> +<meta name="citation_title" content="{{- .Title -}}">
et là une bonne boucle des familles qui prend les trucs tels quels

2024-12-18 09:42 UTC, merged